services:
  postgres:
    container_name: postgres-movies
    image: postgres:13-alpine
    volumes:
      - ./init.sql/:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/postgresql/data
    environment:
      - PGDATABASE=movies
      - POSTGRES_DB=movies
      - PGUSER=admin
      - POSTGRES_USER=admin
      - PGPASSWORD=password
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  pgweb:
    container_name: pgweb-movies
    restart: always
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    links:
      - postgres
    environment:
      - DATABASE_URL=postgres://admin:password@postgres/movies?sslmode=disable

  node-js:
    image: node:16-alpine
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_DB=movies
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    links:
      - postgres
    working_dir: /app
    volumes:
      - ./:/app

volumes:
  db:
